var SentenceData = {
  "lesson": 54,
  "text": "阿女含涙答\n蘭芝初還時\n府吏見丁寜\n結誓不别離\n今日違情義\n恐此事非奇\n自可斷來信\n徐徐更謂之\n阿母白媒人\n貧賤有此女\n始適還家門\n不堪吏人婦\n豈合令郎君\n幸可廣問訊\n不得便相許\n媒人去數日\n尋遣丞請還\n説有蘭家女\n承籍有宦官\n云有第五郎\n蘭芝仰頭答\n理實如兄言\n謝家事夫婿\n中道還兄門\n處分適兄意\n那得自任專\n雖與府吏要\n渠會永無緣\n矯逸未有婚\n遣丞為媒人\n主簿通語言\n直説太守家\n有此令郎君\n既欲結大義\n故遣來貴門\n阿母謝媒人\n女子先有誓\n老姥豈敢言\n阿兄得聞之\n悵然心中煩\n舉言謂阿妹\n作計何不量\n先嫁得府吏\n後嫁得郎君\n否泰如天地\n足以榮汝身\n不嫁異郎體\n其往欲何云\n登即相許和\n便可作婚婣\n媒人下床去\n諾諾複爾爾\n還部白府君\n下官奉使命\n言談大有緣",
  "sentences": [
    { "number": 1, "original": "阿女含涙答", "transliteration": "", "translation": "A filha respondeu com lágrimas:" },
    { "number": 2, "original": "蘭芝初還時", "transliteration": "", "translation": "«Lanzhi acabou de voltar para casa!" },
    { "number": 3, "original": "府吏見丁寜", "transliteration": "", "translation": "O funcionário, ao se despedir, ordenou," },
    { "number": 4, "original": "結誓不别離", "transliteration": "", "translation": "E eu mesma jurei não nos separarmos." },
    { "number": 5, "original": "今日違情義", "transliteration": "", "translation": "Eu não violarei a lealdade a ele." },
    { "number": 6, "original": "恐此事非奇", "transliteration": "", "translation": "Dar o consentimento — é um ato indigno." },
    { "number": 7, "original": "自可斷來信", "transliteration": "", "translation": "Darei uma recusa decisiva ao casamenteiro," },
    { "number": 8, "original": "徐徐更謂之", "transliteration": "", "translation": "Direi que é cedo demais para falar disso»." },
    { "number": 9, "original": "阿母白媒人", "transliteration": "", "translation": "E a mãe disse educadamente ao casamenteiro:" },
    { "number": 10, "original": "貧賤有此女", "transliteration": "", "translation": "«Não, minha filha é pobre e indigna," },
    { "number": 11, "original": "始適還家門", "transliteration": "", "translation": "E o primeiro marido a devolveu para casa." },
    { "number": 12, "original": "不堪吏人婦", "transliteration": "", "translation": "Para um funcionário comum não é par —" },
    { "number": 13, "original": "豈合令郎君", "transliteration": "", "translation": "Será que combina com o filho do nobre?»" },
    { "number": 14, "original": "幸可廣問訊", "transliteration": "", "translation": "Passam os dias desde que o casamenteiro foi embora," },
    { "number": 15, "original": "不得便相許", "transliteration": "", "translation": "E eu, velha, não me atrevo a decidir»." },
    { "number": 16, "original": "媒人去數日", "transliteration": "", "translation": "Passam os dias desde que o casamenteiro foi embora," },
    { "number": 17, "original": "尋遣丞請還", "transliteration": "", "translation": "O governador o envia novamente" },
    { "number": 18, "original": "説有蘭家女", "transliteration": "", "translation": "O casamenteiro voltou à família Liu:" },
    { "number": 19, "original": "承籍有宦官", "transliteration": "", "translation": "Esse é filho de um alto funcionário:" },
    { "number": 20, "original": "云有第五郎", "transliteration": "", "translation": "Diz que o quinto filho dele é bonito," },
    { "number": 21, "original": "蘭芝仰頭答", "transliteration": "", "translation": "Lanzhi respondeu obedientemente:" },
    { "number": 22, "original": "理實如兄言", "transliteration": "", "translation": "«Meu irmão fala com justiça para sua irmã." },
    { "number": 23, "original": "謝家事夫婿", "transliteration": "", "translation": "Deixando a família do marido anterior," },
    { "number": 24, "original": "中道還兄門", "transliteration": "", "translation": "Como exige o dever, voltei à casa paterna" },
    { "number": 25, "original": "處分適兄意", "transliteration": "", "translation": "E devo agir conforme meu irmão ordenar," },
    { "number": 26, "original": "那得自任專", "transliteration": "", "translation": "E não ousarei ser arbitrária." },
    { "number": 27, "original": "雖與府吏要", "transliteration": "", "translation": "Embora tenha dado juramento ao funcionário," },
    { "number": 28, "original": "渠會永無緣", "transliteration": "", "translation": "Mas talvez não nos seja dado nos encontrarmos," },
    { "number": 29, "original": "矯逸未有婚", "transliteration": "", "translation": "Mas até agora não tem esposa." },
    { "number": 30, "original": "遣丞為媒人", "transliteration": "", "translation": "O casamenteiro voltou à família Liu:" },
    { "number": 31, "original": "主簿通語言", "transliteration": "", "translation": "E foi enviado às suas portas»." },
    { "number": 32, "original": "直説太守家", "transliteration": "", "translation": "«Na família do governador há um filho belo," },
    { "number": 33, "original": "有此令郎君", "transliteration": "", "translation": "Esse é filho de um alto funcionário:" },
    { "number": 34, "original": "既欲結大義", "transliteration": "", "translation": "Quer realizar uma cerimônia importante" },
    { "number": 35, "original": "故遣來貴門", "transliteration": "", "translation": "E foi enviado às suas portas»." },
    { "number": 36, "original": "阿母謝媒人", "transliteration": "", "translation": "A mãe respondeu modestamente ao mensageiro:" },
    { "number": 37, "original": "女子先有誓", "transliteration": "", "translation": "«Minha filha se ligou ao marido por juramento," },
    { "number": 38, "original": "老姥豈敢言", "transliteration": "", "translation": "E eu, velha, não me atrevo a decidir»." },
    { "number": 39, "original": "阿兄得聞之", "transliteration": "", "translation": "Com amarga descontentamento, o irmão de Lanzhi se intrometeu" },
    { "number": 40, "original": "悵然心中煩", "transliteration": "", "translation": "Com amarga descontentamento, o irmão de Lanzhi se intrometeu" },
    { "number": 41, "original": "舉言謂阿妹", "transliteration": "", "translation": "E, voltando-se para sua irmã, disse:" },
    { "number": 42, "original": "作計何不量", "transliteration": "", "translation": "«Não seja imprudente em suas decisões:" },
    { "number": 43, "original": "先嫁得府吏", "transliteration": "", "translation": "Seu marido anterior era um funcionário humilde," },
    { "number": 44, "original": "後嫁得郎君", "transliteration": "", "translation": "Esse é filho de um alto funcionário:" },
    { "number": 45, "original": "否泰如天地", "transliteration": "", "translation": "Como céu e terra, eles são diferentes." },
    { "number": 46, "original": "足以榮汝身", "transliteration": "", "translation": "Saiba que com o novo marido a glória a espera," },
    { "number": 47, "original": "不嫁異郎體", "transliteration": "", "translation": "Você está perdendo um marido nobre." },
    { "number": 48, "original": "其往欲何云", "transliteration": "", "translation": "Diga, o que espera e deseja você?»" },
    { "number": 49, "original": "登即相許和", "transliteration": "", "translation": "E eu concordo em me casar novamente»." },
    { "number": 50, "original": "便可作婚婣", "transliteration": "", "translation": "E, confirmando novamente o acordo," },
    { "number": 51, "original": "媒人下床去", "transliteration": "", "translation": "O casamenteiro se levanta apressado e satisfeito" },
    { "number": 52, "original": "諾諾複爾爾", "transliteration": "", "translation": "E, confirmando novamente o acordo," },
    { "number": 53, "original": "還部白府君", "transliteration": "", "translation": "Apressa-se para dar o relatório ao governador:" },
    { "number": 54, "original": "下官奉使命", "transliteration": "", "translation": "«Eu, indigno, cumpri a ordem." },
    { "number": 55, "original": "言談大有緣", "transliteration": "", "translation": "Para o casamento, o destino é favorável»." }
  ]
};